<?php 
    define("head_path","head/");
    define("com_general_path","component/com_general/");
    define("com_idx_path","component/com_idx/");
    define("footer_path","footer/");
    define("com_404_path","component/com_404/");
    define("com_about_path","component/com_about/");
    define("com_blog_path","component/com_blog/");
    define("com_cart_path","component/com_cart/");
    define("com_checkout_path","component/com_checkout/");
    define("com_contact_path","component/com_contact/");
    define("com_fogot_path","component/com_fogot/");
    define("com_login_path","component/com_login/");
    define("com_product_path","component/com_product/");
    define("com_register_path","component/com_register/");
    define("com_shop_path","component/com_shop/");
    define("com_singleBlog_path","component/com_singleBlog/");
    define("com_wishList_path","component/com_wishList/");
    define("img_product_path","img/products/");
    define("img_banner_path","img/banner/");
    define("img_brand_path","img/brand/");
    define("img_logo_path","img/logo/");
    define("img_header_path","img/header/");
    define("img_icon_path","img/icon/");
    define("page_path","page/");
    define("com_compare_path","component/com_compare/");
    define("img_team_path","img/team/");
    define("img_blog_path","img/blog/");
    define("css_path","css/");
    define("js_path","js/vendor/");
    define("img_vertical_path","img/vertical-menu/");
    define("com_profile_path","component/com_Profile/")


?>